INSERT OR REPLACE INTO Unit_FreePromotions (UnitType, 							PromotionType)
VALUES      ('UNIT_ROCKTHROWER',   'PROMOTION_MOUNTED_PENALTY_1'),
         ('UNIT_WARRIOR',   'PROMOTION_MOUNTED_PENALTY_1'),
         ('UNIT_DEFWARRIOR',   'PROMOTION_MOUNTED_PENALTY_1'),
         ('UNIT_ARCHER',   'PROMOTION_MOUNTED_PENALTY_1'),
         ('UNIT_AXE',   'PROMOTION_MOUNTED_PENALTY_1'),
         ('UNIT_SWORDSMAN',   'PROMOTION_MOUNTED_PENALTY_1'); 

-- patch 151023
INSERT OR REPLACE INTO Unit_FreePromotions (UnitType, 							PromotionType)
VALUES      ('UNIT_SCOUT',   'PROMOTION_IGNORE_TERRAIN_COST'),
		    ('UNIT_PATROL',   'PROMOTION_IGNORE_TERRAIN_COST'),
			('UNIT_PATROL',   'PROMOTION_SENTRY'),
			('UNIT_SPEARTHROWER',   'PROMOTION_ONLY_DEFENSIVE'),
			('UNIT_SPEARTHROWER',   'PROMOTION_CITY_PENALTY_2'),
			('UNIT_CHARIOT_ARCHER', 'PROMOTION_ROUGH_TERRAIN_ENDS_TURN'),
			('UNIT_CHARIOT_ARCHER', 'PROMOTION_ONLY_DEFENSIVE'),
			('UNIT_CHARIOT_ARCHER', 'PROMOTION_CITY_PENALTY_2'),
			('UNIT_ARCHER',   'PROMOTION_ONLY_DEFENSIVE'),
			('UNIT_ARCHER',   'PROMOTION_CITY_PENALTY_2');
			/*('UNIT_ROCKTHROWER',   'PROMOTION_MOUNTED_PENALTY_1'),
			('UNIT_ROCKTHROWER',   'PROMOTION_MOUNTED_PENALTY_1'),
			('UNIT_ROCKTHROWER',   'PROMOTION_MOUNTED_PENALTY_1'),
			('UNIT_ROCKTHROWER',   'PROMOTION_MOUNTED_PENALTY_1'),
			('UNIT_ROCKTHROWER',   'PROMOTION_MOUNTED_PENALTY_1'),
			('UNIT_ROCKTHROWER',   'PROMOTION_MOUNTED_PENALTY_1'),
			('UNIT_ROCKTHROWER',   'PROMOTION_MOUNTED_PENALTY_1'),
			('UNIT_ROCKTHROWER',   'PROMOTION_MOUNTED_PENALTY_1');
			
			*/